Create new ArraysAndCycles_hw branch and FirstTask(not end)
Kipyatkovpavel/TMS_AQA pull request #9
Opened 2023-12-10 16:49 UTC by Kipyatkovpavel

Create new ArraysAndCycles_hw branch and FirstTask(not end)

2023-12-11 14:01 UTC, wildpioneer requested changes

2023-12-11 14:01 UTC, wildpioneer commented on FirstTaskArrays/FirstTask.cs
> +            }
Жду остальные задачи

2023-12-12 19:00 UTC, Kipyatkovpavel commented on FirstTaskArrays/FirstTask.cs
> +            }
Да, остальные тоже отгрузил, второе задание, пока под вопросом, остальные вроде как без проблем работают.
Жду с нетерпением вашей проверки.

2023-12-26 08:50 UTC, wildpioneer requested changes

2023-12-26 08:50 UTC, wildpioneer commented on ThirdTask/ThirdTask.cs
> +                Console.WriteLine($"Средние значение в массиве: {array.Average()} ");
Это арифметическое среднее - а надо среднее

2023-12-26 08:50 UTC, wildpioneer commented on FourthTaskArrays/FourthTask.cs
> +            double average1 = array1.Average();
Пойдет - но хотелось все же - чтобы эти значения были найдены самостоятельно, без использования вспомогательных функций

2023-12-26 09:05 UTC, wildpioneer requested changes

2023-12-26 09:05 UTC, wildpioneer commented on SecondTask/SecondTask.cs
> +//Задание не закончено, почему то при удалении числа, он удаляет его из массива, но при этом ставить дополнительный 0 в конце массива.
Данная проблема возникает, потому что у тебя есть ошибка при работе с границами массива. см - коммент выше

2023-12-26 09:05 UTC, wildpioneer commented on SecondTask/SecondTask.cs
> +            for (int i = 0; i < array.GetUpperBound(0); i++)
I <= array.GetUpperBound(0) - при нестрогом равенстве ты теряешь последний элемент и он по умолчанию у тебя становиться 0

2024-01-03 08:53 UTC, Kipyatkovpavel commented on SecondTask/SecondTask.cs
> +            for (int i = 0; i < array.GetUpperBound(0); i++)
Изменил работу с границами массива.
исправление - https://github.com/Kipyatkovpavel/TMS_AQA/commit/e2b0a893235a954241fd5891722726315730e83a

2024-01-29 10:11 UTC, closed without merging